name: sigfq_mobile
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.13.5


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.4.2
  dio: ^5.11.1
  dio_cookie_manager: ^3.5.0
  cookie_jar: ^4.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo-farmacia.png
    - assets/isotipo-farmacia.png